### ISSUE TITLE
Not respecting DO_DIR variable

### ISSUE THREAD

**Issue by kriipke** [laukstein/do-spaces#1]
Hey there! Awesome Action you've created, super useful! 

However, I just wanted to point out that when I used the `DO_DIR` variable it was ignored and the contents of the `LOCAL_DIR` variable was just written to the root of the bucket and it erased everything my bucket.

Fortunately there wasn't anything important in there and I was quickly able to get it back to its original state but the next person may not be so lucky so I wanted to go ahead and say something!

If I'm not using the variable correctly please let me know, the repository in question is https://github.com/kriipke/provii and the workflow file is https://github.com/kriipke/provii/blob/master/.github/workflows/cdn-sync.yml

The bucket had a folder named `provii` at the root and a subfolder named `latest` which I was hoping to have populated by the workflow I just linked to.

Thanks in advance, any and all feedback welcome!

**Comment by laukstein** [comment]
@kriipke sorry for so late response.
I just released v1.0.1 with the fix. Can you please check if it solves your mentioned issue (try to do it on safe (backup) environment).

**Comment by laukstein** [comment]
@kriipke Thanks for your open issue. Sorry for so late my response.
I just released v1.0.1 with the fix. Can you please check if it solves your mentioned issue (try to do it on safe (backup) environment) ?
